---

- name: Management Controller for Ubiquiti Networks UniFi APs - accept required licenses
  ansible.builtin.lineinfile:
    path: /etc/portage/package.license
    regexp: '^{{ item.package }}'
    line: '{{ item.package }} {{ item.license }}'
    create: yes
  become: yes
  loop:
    - { package: net-wireless/unifi, license:  ubiquiti }
    - { package: dev-db/mongodb, license: SSPL-1 }

- name: Management Controller for Ubiquiti Networks UniFi APs - unmask required packages
  ansible.builtin.template:
    src: unifi.accept_keywords.j2
    dest: /etc/portage/package.accept_keywords/60-unifi
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Management Controller for Ubiquiti Networks UniFi APs - install package
  ansible.builtin.package:
    name: net-wireless/unifi
    changed_use: yes
  become: yes

- name: Management Controller for Ubiquiti Networks UniFi APs - install package - start and enable SystemD service
  ansible.builtin.systemd:
    name: unifi
    state: started
    enabled: yes
  become: yes
